"""Add missing impact columns to behaviors

Revision ID: 8dfd9a133290
Revises: 
Create Date: 2026-02-02 16:27:49.325605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8dfd9a133290'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_completion_logs_behavior_id', table_name='completion_logs')
    op.drop_index('idx_completion_logs_completed_at', table_name='completion_logs')
    op.drop_index('idx_completion_logs_optimization_run_id', table_name='completion_logs')
    op.drop_index('idx_completion_logs_user_id', table_name='completion_logs')
    op.drop_table('completion_logs')
    op.drop_index('idx_constraints_type', table_name='constraints')
    op.drop_index('idx_constraints_user_id', table_name='constraints')
    op.drop_table('constraints')
    op.drop_index('idx_optimization_runs_created_at', table_name='optimization_runs')
    op.drop_index('idx_optimization_runs_status', table_name='optimization_runs')
    op.drop_index('idx_optimization_runs_user_id', table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_objectives_type', table_name='objectives')
    op.drop_index('idx_objectives_user_id', table_name='objectives')
    op.drop_table('objectives')
    op.drop_index('idx_behaviors_category', table_name='behaviors')
    op.drop_index('idx_behaviors_is_active', table_name='behaviors')
    op.drop_index('idx_behaviors_user_id', table_name='behaviors')
    op.drop_table('behaviors')
    op.drop_index('idx_scheduled_behaviors_behavior_id', table_name='scheduled_behaviors')
    op.drop_index('idx_scheduled_behaviors_optimization_run_id', table_name='scheduled_behaviors')
    op.drop_table('scheduled_behaviors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_behaviors',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('optimization_run_id', sa.CHAR(length=32), nullable=False),
    sa.Column('behavior_id', sa.CHAR(length=32), nullable=False),
    sa.Column('time_period', sa.INTEGER(), nullable=False),
    sa.Column('scheduled_duration', sa.INTEGER(), nullable=False),
    sa.Column('is_scheduled', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_behaviors_optimization_run_id', 'scheduled_behaviors', ['optimization_run_id'], unique=False)
    op.create_index('idx_scheduled_behaviors_behavior_id', 'scheduled_behaviors', ['behavior_id'], unique=False)
    op.create_table('behaviors',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=12), nullable=False),
    sa.Column('min_duration', sa.INTEGER(), nullable=False),
    sa.Column('typical_duration', sa.INTEGER(), nullable=False),
    sa.Column('max_duration', sa.INTEGER(), nullable=False),
    sa.Column('energy_cost', sa.FLOAT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('preferred_time_slots', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('impact_on_health', sa.FLOAT(), nullable=False),
    sa.Column('impact_on_productivity', sa.FLOAT(), nullable=False),
    sa.Column('impact_on_learning', sa.FLOAT(), nullable=False),
    sa.Column('impact_on_wellness', sa.FLOAT(), nullable=False),
    sa.Column('impact_on_social', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_behaviors_user_id', 'behaviors', ['user_id'], unique=False)
    op.create_index('idx_behaviors_is_active', 'behaviors', ['is_active'], unique=False)
    op.create_index('idx_behaviors_category', 'behaviors', ['category'], unique=False)
    op.create_table('objectives',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('type', sa.VARCHAR(length=12), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_objectives_user_id', 'objectives', ['user_id'], unique=False)
    op.create_index('idx_objectives_type', 'objectives', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('solver', sa.VARCHAR(length=12), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('time_periods', sa.INTEGER(), nullable=False),
    sa.Column('results', sqlite.JSON(), nullable=True),
    sa.Column('diagnostics', sqlite.JSON(), nullable=True),
    sa.Column('total_objective_value', sa.FLOAT(), nullable=True),
    sa.Column('execution_time_seconds', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_optimization_runs_user_id', 'optimization_runs', ['user_id'], unique=False)
    op.create_index('idx_optimization_runs_status', 'optimization_runs', ['status'], unique=False)
    op.create_index('idx_optimization_runs_created_at', 'optimization_runs', ['created_at'], unique=False)
    op.create_table('constraints',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('parameters', sqlite.JSON(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_constraints_user_id', 'constraints', ['user_id'], unique=False)
    op.create_index('idx_constraints_type', 'constraints', ['type'], unique=False)
    op.create_table('completion_logs',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('behavior_id', sa.CHAR(length=32), nullable=False),
    sa.Column('optimization_run_id', sa.CHAR(length=32), nullable=True),
    sa.Column('actual_duration', sa.INTEGER(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=False),
    sa.Column('satisfaction_score', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_completion_logs_user_id', 'completion_logs', ['user_id'], unique=False)
    op.create_index('idx_completion_logs_optimization_run_id', 'completion_logs', ['optimization_run_id'], unique=False)
    op.create_index('idx_completion_logs_completed_at', 'completion_logs', ['completed_at'], unique=False)
    op.create_index('idx_completion_logs_behavior_id', 'completion_logs', ['behavior_id'], unique=False)
    # ### end Alembic commands ###
