"""initial migration

Revision ID: b96cd1f49448
Revises: 
Create Date: 2026-02-05 18:20:00.617201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b96cd1f49448'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('behaviors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('HEALTH', 'PRODUCTIVITY', 'LEARNING', 'WELLNESS', 'SOCIAL', 'FINANCIAL', 'CREATIVITY', 'MINDFULNESS', name='behaviorcategory'), nullable=False),
    sa.Column('min_duration', sa.Integer(), nullable=False),
    sa.Column('typical_duration', sa.Integer(), nullable=False),
    sa.Column('max_duration', sa.Integer(), nullable=False),
    sa.Column('energy_cost', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferred_time_slots', postgresql.ARRAY(sa.Enum('EARLY_MORNING', 'MORNING', 'MIDDAY', 'AFTERNOON', 'EVENING', 'NIGHT', 'FLEXIBLE', name='timeslot')), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('impact_on_health', sa.Float(), nullable=False),
    sa.Column('impact_on_productivity', sa.Float(), nullable=False),
    sa.Column('impact_on_learning', sa.Float(), nullable=False),
    sa.Column('impact_on_wellness', sa.Float(), nullable=False),
    sa.Column('impact_on_social', sa.Float(), nullable=False),
    sa.Column('impact_on_financial', sa.Float(), nullable=False),
    sa.Column('impact_on_creativity', sa.Float(), nullable=False),
    sa.Column('impact_on_mindfulness', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_behaviors_category', 'behaviors', ['category'], unique=False)
    op.create_index('idx_behaviors_is_active', 'behaviors', ['is_active'], unique=False)
    op.create_index('idx_behaviors_user_id', 'behaviors', ['user_id'], unique=False)
    op.create_table('constraints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('TIME_BUDGET', 'FREQUENCY', 'DURATION_BOUNDS', 'PRECEDENCE', 'MUTUAL_EXCLUSION', name='constrainttype'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_constraints_type', 'constraints', ['type'], unique=False)
    op.create_index('idx_constraints_user_id', 'constraints', ['user_id'], unique=False)
    op.create_table('objectives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('HEALTH', 'PRODUCTIVITY', 'LEARNING', 'WELLNESS', 'SOCIAL', 'FINANCIAL', 'CREATIVITY', 'MINDFULNESS', name='objectivetype'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_objectives_type', 'objectives', ['type'], unique=False)
    op.create_index('idx_objectives_user_id', 'objectives', ['user_id'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='optimizationstatus'), nullable=False),
    sa.Column('solver', sa.Enum('LINEAR', 'NONLINEAR', 'HEURISTIC', 'EVOLUTIONARY', name='solvertype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('time_periods', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('diagnostics', sa.JSON(), nullable=True),
    sa.Column('total_objective_value', sa.Float(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_optimization_runs_created_at', 'optimization_runs', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_optimization_runs_status', 'optimization_runs', ['status'], unique=False)
    op.create_index('idx_optimization_runs_user_id', 'optimization_runs', ['user_id'], unique=False)
    op.create_table('completion_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('behavior_id', sa.Uuid(), nullable=False),
    sa.Column('optimization_run_id', sa.Uuid(), nullable=True),
    sa.Column('actual_duration', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_completion_logs_behavior_id', 'completion_logs', ['behavior_id'], unique=False)
    op.create_index('idx_completion_logs_completed_at', 'completion_logs', ['completed_at'], unique=False)
    op.create_index('idx_completion_logs_optimization_run_id', 'completion_logs', ['optimization_run_id'], unique=False)
    op.create_index('idx_completion_logs_user_id', 'completion_logs', ['user_id'], unique=False)
    op.create_table('scheduled_behaviors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('optimization_run_id', sa.Uuid(), nullable=False),
    sa.Column('behavior_id', sa.Uuid(), nullable=False),
    sa.Column('time_period', sa.Integer(), nullable=False),
    sa.Column('scheduled_duration', sa.Integer(), nullable=False),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_behaviors_behavior_id', 'scheduled_behaviors', ['behavior_id'], unique=False)
    op.create_index('idx_scheduled_behaviors_optimization_run_id', 'scheduled_behaviors', ['optimization_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scheduled_behaviors_optimization_run_id', table_name='scheduled_behaviors')
    op.drop_index('idx_scheduled_behaviors_behavior_id', table_name='scheduled_behaviors')
    op.drop_table('scheduled_behaviors')
    op.drop_index('idx_completion_logs_user_id', table_name='completion_logs')
    op.drop_index('idx_completion_logs_optimization_run_id', table_name='completion_logs')
    op.drop_index('idx_completion_logs_completed_at', table_name='completion_logs')
    op.drop_index('idx_completion_logs_behavior_id', table_name='completion_logs')
    op.drop_table('completion_logs')
    op.drop_index('idx_optimization_runs_user_id', table_name='optimization_runs')
    op.drop_index('idx_optimization_runs_status', table_name='optimization_runs')
    op.drop_index('idx_optimization_runs_created_at', table_name='optimization_runs', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('optimization_runs')
    op.drop_index('idx_objectives_user_id', table_name='objectives')
    op.drop_index('idx_objectives_type', table_name='objectives')
    op.drop_table('objectives')
    op.drop_index('idx_constraints_user_id', table_name='constraints')
    op.drop_index('idx_constraints_type', table_name='constraints')
    op.drop_table('constraints')
    op.drop_index('idx_behaviors_user_id', table_name='behaviors')
    op.drop_index('idx_behaviors_is_active', table_name='behaviors')
    op.drop_index('idx_behaviors_category', table_name='behaviors')
    op.drop_table('behaviors')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
